# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages: 
- stage: Build 
  displayName: 'Build' 

  jobs: 
    - job: BuildDEV 
      pool: 
        vmImage: 'windows-latest'

- stage: DeployDEV 
  displayName: 'Deploy Development' 

  jobs: 
  - deployment: Deploy 
    displayName: 'Deploy Development' 
    pool: 
      vmImage: 'windows-latest' 
    environment: 'Development' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - download: none 
          - task: PowerShell@2 
            inputs: 
              targetType: 'inline' 
              script: | 
                # Write your PowerShell commands here. 
                Write-Host "Deploy in Development" 
- stage: DeployQA 
  displayName: 'Deploy QA' 

  jobs: 
  - deployment: Deploy 
    displayName: 'Deploy QA' 
    pool: 
      vmImage: 'windows-latest' 
    environment: 'QA' 
    strategy: 
      runOnce: 
        deploy: 
          steps: 
          - download: none 
          - task: PowerShell@2 
            inputs: 
              targetType: 'inline' 
              script: | 
                # Write your PowerShell commands here. 
                Write-Host "Deploy in QA" 